### ISSUE TITLE
Demos broken

### ISSUE THREAD

**Issue by IvanSanchez** [IvanSanchez/Leaflet.Marker.Stack#2]
Due to #1, @nerik put the demos in a subdirectory, but he forgot to replace the path of the plugin files (from `Leaflet.Marker.Stack.js` to `../Leaflet.Marker.Stack.js`), and so the demos won't work.

**Comment by nerik** [comment]
Fixed in https://github.com/IvanSanchez/Leaflet.Marker.Stack/pulls
